import Link from "next/link";
import {
  CalendarClock,
  Clock,
  Handshake,
  Mail,
  UserCheck,
} from "lucide-react";

import { AppShell } from "@/components/layout/app-shell";
import { PageHeader } from "@/components/page-header";
import { Badge } from "@/components/ui/badge";
import { Card, CardBody } from "@/components/ui/card";
import { prisma } from "@/lib/db";
import { fmtDate } from "@/lib/utils";

export const dynamic = "force-dynamic";

const ACTION_TYPE_META: Record<string, { icon: React.ElementType; tone: "warning" | "danger" | "info" | "neutral"; label: string }> = {
  SendInvite:          { icon: Mail,         tone: "info",    label: "초대 발송" },
  SendReminder:        { icon: Clock,        tone: "warning", label: "리마인드" },
  ScheduleMeeting:     { icon: Handshake,    tone: "info",    label: "미팅 예약" },
  PostEventFollowUp:   { icon: CalendarClock, tone: "neutral", label: "팔로업" },
  AssignOwner:         { icon: UserCheck,    tone: "danger",  label: "담당자 배정" },
};

const SEED_ITEMS = [
  {
    id: "seed-1",
    cmid: null,
    actionType: "SendInvite",
    priority: 2,
    reason: "Max Summit 2026 초대 미발송 광고주 (tier A)",
    dueBy: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    status: "Open",
    autoGenerated: true,
  },
  {
    id: "seed-2",
    cmid: null,
    actionType: "SendReminder",
    priority: 2,
    reason: "초대 후 7일 무응답 — 리마인드 필요",
    dueBy: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    status: "Open",
    autoGenerated: true,
  },
  {
    id: "seed-3",
    cmid: null,
    actionType: "AssignOwner",
    priority: 1,
    reason: "A등급 광고주 담당자 미배정",
    dueBy: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    status: "Open",
    autoGenerated: true,
  },
  {
    id: "seed-4",
    cmid: null,
    actionType: "ScheduleMeeting",
    priority: 3,
    reason: "참석 확정 후 미팅 미설정",
    dueBy: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    status: "InProgress",
    autoGenerated: true,
  },
];

export default async function ActionsPage() {
  let items = await prisma.actionItem.findMany({
    orderBy: [{ priority: "asc" }, { dueBy: "asc" }],
    take: 20,
    where: { status: { in: ["Open", "InProgress"] } },
  });

  const usingSeeds = items.length === 0;
  const displayItems = usingSeeds
    ? SEED_ITEMS
    : items;

  return (
    <AppShell>
      <PageHeader
        eyebrow="Sales Solution Agent"
        title="다음 액션 큐"
        description="룰 엔진이 KB 상태를 스캔하여 자동 생성한 액션. Cron (매일 04:00 KST) + 이벤트 트리거로 실시간 갱신."
        breadcrumbs={[
          { href: "/", label: "홈" },
          { href: "/agent", label: "Agent" },
          { label: "액션 큐" },
        ]}
      />

      <div className="mb-4 flex items-center gap-3">
        <Badge tone={usingSeeds ? "neutral" : "lime"}>
          {usingSeeds ? "샘플 데이터" : `${displayItems.length}건`}
        </Badge>
        {!usingSeeds && (
          <span className="text-xs text-[color:var(--color-muted-foreground)]">
            Open / InProgress 액션 {displayItems.length}건
          </span>
        )}
        {usingSeeds && (
          <span className="text-xs text-[color:var(--color-muted-foreground)]">
            실제 ActionItem 데이터 없음 — 샘플 표시 중
          </span>
        )}
      </div>

      <div className="space-y-3">
        {displayItems.map((item) => {
          const meta = ACTION_TYPE_META[item.actionType] ?? {
            icon: Mail,
            tone: "neutral" as const,
            label: item.actionType,
          };
          const Icon = meta.icon;
          const isOverdue = item.dueBy && item.dueBy < new Date();
          return (
            <Card key={item.id}>
              <CardBody>
                <div className="flex items-start gap-3">
                  <div
                    className={
                      meta.tone === "danger"
                        ? "size-9 rounded-md bg-[color:var(--color-danger-bg)] text-[color:var(--color-danger)] flex items-center justify-center shrink-0"
                        : meta.tone === "info"
                          ? "size-9 rounded-md bg-[color:var(--color-info-bg)] text-[color:var(--color-info)] flex items-center justify-center shrink-0"
                          : meta.tone === "warning"
                            ? "size-9 rounded-md bg-[color:var(--color-warning-bg)] text-[color:var(--color-warning)] flex items-center justify-center shrink-0"
                            : "size-9 rounded-md bg-[color:var(--color-muted)] text-[color:var(--color-muted-foreground)] flex items-center justify-center shrink-0"
                    }
                  >
                    <Icon className="size-5" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className="font-semibold text-sm">{meta.label}</span>
                      <Badge tone={meta.tone as "warning"}>P{item.priority}</Badge>
                      <Badge tone={item.status === "InProgress" ? "lime" : "neutral"}>
                        {item.status}
                      </Badge>
                      {isOverdue && <Badge tone="danger">기한 초과</Badge>}
                    </div>
                    {item.reason && (
                      <p className="text-xs text-[color:var(--color-muted-foreground)] mt-1">
                        {item.reason}
                      </p>
                    )}
                    <div className="flex items-center gap-3 mt-2">
                      {item.dueBy && (
                        <span className="text-[11px] text-[color:var(--color-muted-foreground)]">
                          마감: {fmtDate(item.dueBy)}
                        </span>
                      )}
                      {item.cmid && (
                        <Link
                          href={`/accounts/${item.cmid}`}
                          className="text-[11px] text-[color:var(--color-brand-ink)] hover:underline"
                        >
                          광고주 보기
                        </Link>
                      )}
                      {item.cmid && item.actionType !== "AssignOwner" && (
                        <Link
                          href={`/agent/messages?cmid=${item.cmid}&purpose=${
                            item.actionType === "SendInvite" ? "Invitation"
                            : item.actionType === "SendReminder" ? "Reminder"
                            : item.actionType === "PostEventFollowUp" ? "PostEvent"
                            : "FollowUp"
                          }`}
                          className="inline-flex items-center gap-1 text-xs bg-[color:var(--color-brand-ink)] text-white px-2.5 h-7 rounded-md hover:bg-[color:var(--color-brand-ink-2)]"
                        >
                          메시지 작성
                        </Link>
                      )}
                    </div>
                  </div>
                </div>
              </CardBody>
            </Card>
          );
        })}
      </div>
    </AppShell>
  );
}
